name: Entrenamiento
on: [push]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Pull Images
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc pull ./assets/images/Feature_Importance.png ./assets/images/F_vs_t.png

      - name: Create CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Comparación de Resultados de Entrenamiento" >> report.md
          dvc metrics diff master --md >> report.md
          
          echo "##  Feature Importance (Coeficientes LR)" >> report.md
          cml publish ./assets/images/Feature_Importance.png --md >> report.md
          
          echo "##  True vs Fitted Curve" >> report.md
          cml publish ./assets/images/F_vs_t.png --md >> report.md
          
          cml send-comment report.md